# Generated by Django 4.2.7 on 2023-11-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
                ('dominio', models.CharField(max_length=100)),
                ('effetto', models.TextField(max_length=500)),
                ('puntiVita', models.IntegerField()),
            ],
        ),
    ]
