# Generated by Django 4.2.7 on 2023-11-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_carta_costo_alter_carta_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='elemento',
            field=models.CharField(choices=[('Fuoco', 'Fuoco'), ('Terra', 'Terra'), ('Acqua', 'Acqua'), ('Aria', 'Aria')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='carta',
            name='puntiVita',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carta',
            name='tipo',
            field=models.CharField(blank=True, choices=[('avatar', 'avatar'), ('minion', 'minion'), ('magia', 'magia'), ('sito', 'sito')], default='', max_length=100),
        ),
    ]
